<?php

namespace Tests\Feature;

use App\Servicos\CriadorDeSerie;
use App\Servicos\RemovedorSerie;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RemovedorDeSerieTest extends TestCase
{
    use RefreshDatabase;

    private $serie;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $criadorDeSerie = new CriadorDeSerie();

        $this->serie = $criadorDeSerie->criarSerie(
            'Nome da Série',
            2,
            2
        );


    }

    public function testRemoverUmaSerie()
    {
        $this->assertDatabaseHas(
            'series',
            ['id'=>$this->serie->id]
        );
        $removedorDeSerie = new RemovedorSerie();
        $nomeSerie=$removedorDeSerie->removerSerie($this->serie->id);
        $this->assertIsString($nomeSerie);
        $this->assertEquals('Nome da Série',$this->serie->nome);
        $this->assertDatabaseMissing(
            'series',
            ['id'=>$this->serie->id]
        );
    }
}
